# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
import os
import json
from calm.dsl.runbooks import *
from calm.dsl.runbooks import (
    CalmEndpoint as Endpoint,
    RunbookTask as CalmTask,
    RunbookVariable as CalmVariable,
)
from calm.dsl.builtins import CalmTask as CalmVarTask, Metadata

# Endpoints
WindowsEndpoint = Endpoint.use_existing("WindowsEndpoint")
LinuxEndpoint = Endpoint.use_existing("LinuxEndpoint")


# Runbook
@runbook
def VMHealthCheckRunbook():

    CalmTask.Exec.powershell(
        name="WindowsDiskStats",
        filename=os.path.join(
            "scripts", "_Runbook_VMHealthCheckRunbook_Task_WindowsDiskStats.ps1"
        ),
        target=ref(WindowsEndpoint),
    )

    CalmTask.Exec.powershell(
        name="WindowsRAMCPUStats",
        filename=os.path.join(
            "scripts", "_Runbook_VMHealthCheckRunbook_Task_WindowsRAMCPUStats.ps1"
        ),
        target=ref(WindowsEndpoint),
    )

    CalmTask.Exec.ssh(
        name="LinuxVMStatus",
        filename=os.path.join(
            "scripts", "_Runbook_VMHealthCheckRunbook_Task_LinuxVMStatus.sh"
        ),
        target=ref(LinuxEndpoint),
    )
    
    RunbookTask.Exec.ssh(
            name="LinuxGetDiskUsage",
            filename=os.path.join('scripts', '_Runbook_VMHealthCheckRunbook_Task_LinuxGetDiskUsage.sh'),
            target=ref(Endpoint.use_existing("LinuxEndpoint")),
        )


class RunbookMetadata(Metadata):
    project = Ref.Project("hack_demo_project")
