# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated blueprint DSL (.py)
"""

import json  # no_qa
import os  # no_qa

from calm.dsl.builtins import CalmTask as CalmVarTask
from calm.dsl.builtins import *  # no_qa
from calm.dsl.runbooks import CalmEndpoint as Endpoint

BP_CRED_BasicLinuxVM_Credential_PASSWORD = read_local_file(
    "BP_CRED_BasicLinuxVM_Credential_PASSWORD"
)

# Credentials
BP_CRED_BasicLinuxVM_Credential = basic_cred(
    "root",
    BP_CRED_BasicLinuxVM_Credential_PASSWORD,
    name="BasicLinuxVM_Credential",
    type="PASSWORD",
    default=True,
)


class BasicLinuxVM_Service(Service):

    pass


class calm_application_namecalm_array_indexResources(AhvVmResources):

    memory = 1
    vCPUs = 1
    cores_per_vCPU = 1
    disks = [
        AhvVmDisk.Disk.Scsi.cloneFromImageService("Centos7HadoopMaster", bootable=True)
    ]
    nics = [
        AhvVmNic.NormalNic.ingress("valn1211", cluster="auto_cluster_prod_e9af58ad7f61")
    ]

    power_state = "ON"


class calm_application_namecalm_array_index(AhvVm):

    name = "{{calm_application_name}}-{{calm_array_index}}"
    resources = calm_application_namecalm_array_indexResources
    cluster = Ref.Cluster(name="auto_cluster_prod_e9af58ad7f61")


class BasicLinuxVM_Substrate(Substrate):

    os_type = "Linux"
    provider_type = "AHV_VM"
    provider_spec = calm_application_namecalm_array_index

    readiness_probe = readiness_probe(
        connection_type="", disabled=True, retries="5", delay_secs="60"
    )


class BasicLinuxVM_Package(Package):

    services = [ref(BasicLinuxVM_Service)]


class BasicLinuxVM_Deployment(Deployment):

    min_replicas = "1"
    max_replicas = "1"

    packages = [ref(BasicLinuxVM_Package)]
    substrate = ref(BasicLinuxVM_Substrate)


class BasicLinuxVM_AppProfile(Profile):

    deployments = [BasicLinuxVM_Deployment]


class BasicLinuxVM(Blueprint):

    services = [BasicLinuxVM_Service]
    packages = [BasicLinuxVM_Package]
    substrates = [BasicLinuxVM_Substrate]
    profiles = [BasicLinuxVM_AppProfile]
    credentials = [BP_CRED_BasicLinuxVM_Credential]


class BpMetadata(Metadata):

    categories = {"TemplateType": "Vm"}
